export type Aircraft = {
  slug: string;
  name: string;
  designation: string;
  nation: 'United Kingdom' | 'United States' | 'Soviet Union' | 'Germany' | 'Japan' | 'Italy';
  role: string;
  manufacturer: string;
  firstFlight: string;
  inService: string;
  produced: string;
  crew: string;
  engine: string;
  maxSpeed: string;
  ceiling: string;
  range: string;
  armament: string;
  tagline: string;
  summary: string;
  history: string[];
  notableOperators: string[];
  theaters: string[];
  image: string;
  imageCredit: string;
  /** Wikipedia article slug used to fetch a confirmed thumbnail via the Wikipedia REST API. */
  wikiSlug: string;
  tags: string[];
};

// Images use Wikimedia Commons' stable Special:FilePath endpoint.
// To replace an image, swap the filename in the URL with a different
// Commons file (or any URL — remotePatterns in next.config.js allows wildcards).
const wm = (file: string) =>
  `/api/img?file=${encodeURIComponent(file)}&w=1200`;

export const aircraft: Aircraft[] = [
  // ──────────────── UNITED KINGDOM ────────────────
  {
    slug: 'supermarine-spitfire',
    name: 'Supermarine Spitfire',
    designation: 'Mk.I — Mk.24',
    nation: 'United Kingdom',
    role: 'Single-seat fighter / interceptor',
    manufacturer: 'Supermarine',
    firstFlight: '5 March 1936',
    inService: '1938 – 1955',
    produced: '≈ 20,351',
    crew: '1',
    engine: 'Rolls-Royce Merlin / Griffon V12',
    maxSpeed: '594 km/h (Mk.IX) — 730 km/h (Mk.24)',
    ceiling: '11,300 m',
    range: '1,840 km (with drop tank)',
    armament: '2× 20 mm Hispano cannon, 4× .303 Browning MGs; up to 454 kg bombs',
    tagline: 'The elliptical silhouette that came to mean Britain itself.',
    summary:
      'The Spitfire is perhaps the most iconic Allied fighter of the war — an elegant, high-performance monoplane designed by R.J. Mitchell around the Rolls-Royce Merlin engine. Its elliptical wing, a marvel of aerodynamics, gave it a combination of speed, climb, and manoeuvrability that matched or exceeded almost any contemporary. It fought in every theatre the RAF touched.',
    history: [
      'Entered squadron service in August 1938 with No. 19 Squadron at Duxford. Outnumbered by the more rugged Hurricane during the Battle of Britain, the Spitfire was nevertheless used to engage German fighter cover, allowing Hurricanes to fall on the bombers.',
      'Underwent continuous development — from the Merlin-engined Mk.I/II/V/IX to the far more powerful Griffon-engined marks — which kept it competitive against successive generations of German fighters including the Bf 109F/G/K and the formidable Fw 190.',
      'Variants served as high-altitude interceptors, photo-reconnaissance platforms (unarmed, polished, and extremely fast), carrier-borne Seafires for the Royal Navy, and fighter-bombers during the push into Europe. Production did not cease until 1948.',
    ],
    notableOperators: ['RAF', 'Fleet Air Arm', 'USAAF', 'Royal Australian Air Force', 'Soviet VVS'],
    theaters: ['Western Europe', 'Mediterranean', 'North Africa', 'Pacific', 'Burma'],
    image: wm('Supermarine_Spitfire_Mk_Vb_of_92_Sqn_flown_by_Geoffrey_Wellum_1941.jpg'),
    imageCredit: 'Royal Air Force official photographer / IWM — Public Domain',
    wikiSlug: 'Supermarine_Spitfire',
    tags: ['Fighter', 'Iconic', 'RAF', 'Battle of Britain'],
  },
  {
    slug: 'hawker-hurricane',
    name: 'Hawker Hurricane',
    designation: 'Mk.I — Mk.IV',
    nation: 'United Kingdom',
    role: 'Fighter / fighter-bomber',
    manufacturer: 'Hawker Aircraft',
    firstFlight: '6 November 1935',
    inService: '1937 – 1947',
    produced: '14,487',
    crew: '1',
    engine: 'Rolls-Royce Merlin II / III / XX',
    maxSpeed: '547 km/h',
    ceiling: '10,970 m',
    range: '965 km',
    armament: '8× .303 Brownings (later 4× 20 mm cannon or 2× 40 mm anti-tank guns)',
    tagline: 'The workhorse that actually won the Battle of Britain.',
    summary:
      'Though the Spitfire got the glory, it was the Hurricane that shot down more enemy aircraft in the Battle of Britain than all other defences combined. Its steel-tube-and-fabric construction was old-fashioned but tough, easy to repair in the field, and surprisingly battle-tolerant — holes in fabric panels could be patched in minutes.',
    history: [
      'Designed by Sydney Camm as a monoplane successor to the Hawker Fury biplane. Entered service in December 1937 — the RAF\'s first modern monoplane fighter and its first aircraft capable of 300 mph in level flight.',
      'During the Battle of Britain, Hurricane squadrons were typically directed against German bomber formations while Spitfires engaged the fighter escort. Its stable gun platform and eight-Browning armament were devastating against the Do 17, He 111, and Ju 88.',
      'Later marks adapted the airframe for nearly every role imaginable: ground-attack Hurribombers, tropical versions for North Africa, naval Sea Hurricanes launched from catapult-equipped merchantmen, and the remarkable Mk.IID tank-buster with 40 mm Vickers S cannons slung under the wings.',
    ],
    notableOperators: ['RAF', 'Soviet VVS', 'Royal Canadian Air Force', 'Fleet Air Arm'],
    theaters: ['Western Europe', 'Mediterranean', 'North Africa', 'Eastern Front', 'Burma'],
    image: wm('Hawker_Hurricane_Mk_I_of_No._85_Squadron_RAF_in_flight_October_1940.jpg'),
    imageCredit: 'Royal Air Force official photographer / IWM — Public Domain',
    wikiSlug: 'Hawker_Hurricane',
    tags: ['Fighter', 'RAF', 'Battle of Britain', 'Ground-attack'],
  },
  {
    slug: 'avro-lancaster',
    name: 'Avro Lancaster',
    designation: 'B.I / B.III / B.X',
    nation: 'United Kingdom',
    role: 'Heavy night bomber',
    manufacturer: 'Avro',
    firstFlight: '9 January 1941',
    inService: '1942 – 1963',
    produced: '7,377',
    crew: '7',
    engine: '4× Rolls-Royce Merlin XX / 24 V12',
    maxSpeed: '454 km/h',
    ceiling: '6,500 m (loaded)',
    range: '4,073 km',
    armament: '8× .303 Brownings in three turrets; up to 10,000 kg bomb load (22,000 lb with Grand Slam)',
    tagline: 'The aircraft that carried Bomber Command to Berlin — and beyond.',
    summary:
      'Born from the failure of the twin-engine Manchester, the four-engined Lancaster became the backbone of RAF Bomber Command\'s night offensive against Germany. Its cavernous bomb bay was uniquely adaptable, eventually accepting ordnance no other aircraft in the world could lift — including the 12,000 lb Tallboy and 22,000 lb Grand Slam earthquake bombs.',
    history: [
      'First operational sortie on 3 March 1942. Over the course of the war, Lancasters flew some 156,000 operational sorties and delivered more than 608,000 tonnes of bombs.',
      'Famous for 617 Squadron\'s "Dambusters" raid of May 1943, using Barnes Wallis\'s bouncing bomb to breach the Möhne and Eder dams. The same squadron later used Tallboy to sink the battleship Tirpitz and to destroy heavily-buried U-boat pens.',
      'A brutal occupation: of the 7,377 Lancasters built, over 3,500 were lost on operations. Of Bomber Command\'s 125,000 aircrew, more than 55,000 were killed — a casualty rate unmatched among Allied forces.',
    ],
    notableOperators: ['RAF Bomber Command', 'Royal Canadian Air Force', 'Royal Australian Air Force'],
    theaters: ['Western Europe — strategic bombing'],
    image: wm('Avro_Lancaster_B_I_PA474.jpg'),
    imageCredit: 'Wikimedia Commons — CC BY-SA',
    wikiSlug: 'Avro_Lancaster',
    tags: ['Bomber', 'RAF', 'Strategic bombing', 'Heavy'],
  },
  {
    slug: 'de-havilland-mosquito',
    name: 'de Havilland Mosquito',
    designation: 'Mk.I — Mk.41',
    nation: 'United Kingdom',
    role: 'Multi-role: bomber, night fighter, recce, intruder',
    manufacturer: 'de Havilland',
    firstFlight: '25 November 1940',
    inService: '1941 – 1963',
    produced: '7,781',
    crew: '2',
    engine: '2× Rolls-Royce Merlin V12',
    maxSpeed: '668 km/h',
    ceiling: '11,000 m',
    range: '2,400 km',
    armament: 'Varies: 4× 20 mm cannon + 4× .303 MGs (FB.VI); up to 1,800 kg bomb load',
    tagline: '"The Wooden Wonder" — faster unarmed than most fighters armed.',
    summary:
      'The Mosquito was a radical gamble: a twin-Merlin bomber built almost entirely from moulded plywood and balsa. De Havilland believed speed alone could be its defence, and they were right — the early bomber variants simply outran any interceptor in the sky. It became one of the most versatile aircraft of the war.',
    history: [
      'Conceived privately by de Havilland when the Air Ministry was uninterested. Early variants were so fast that bomber versions dispensed with defensive guns entirely. Photo-reconnaissance Mosquitoes could stroll over the Reich with near-impunity.',
      'Fighter-bomber FB.VIs became the low-level precision weapon of choice, carrying out pinpoint strikes such as the Amiens prison raid (Operation Jericho, 1944), the attack on Gestapo headquarters in Copenhagen, and the Aarhus university raid.',
      'Night-fighter variants fitted with AI radar became lethal hunters of German intruders over Britain and later of Luftwaffe aircraft over Germany itself. Mosquito pilots and navigators accounted for over 600 aerial victories at night.',
    ],
    notableOperators: ['RAF', 'Royal Canadian Air Force', 'USAAF'],
    theaters: ['Western Europe', 'Mediterranean', 'Pacific'],
    image: wm('De_Havilland_DH-98_Mosquito_B_XVI_ML963.jpg'),
    imageCredit: 'Royal Air Force / IWM — Public Domain',
    wikiSlug: 'De_Havilland_Mosquito',
    tags: ['Multi-role', 'RAF', 'Fast bomber', 'Night fighter'],
  },
  {
    slug: 'hawker-typhoon',
    name: 'Hawker Typhoon',
    designation: 'Mk.IB',
    nation: 'United Kingdom',
    role: 'Fighter-bomber / ground-attack',
    manufacturer: 'Hawker Aircraft',
    firstFlight: '24 February 1940',
    inService: '1941 – 1945',
    produced: '3,317',
    crew: '1',
    engine: 'Napier Sabre IIA H-24 (2,180 hp)',
    maxSpeed: '663 km/h',
    ceiling: '10,400 m',
    range: '820 km',
    armament: '4× 20 mm Hispano cannon; 8× RP-3 rockets or 2× 500 lb bombs',
    tagline: 'The rocket-firing nemesis of every German tank column in Normandy.',
    summary:
      'The Typhoon was troubled at first — unreliable Sabre engine, structural failures in the rear fuselage — but once these problems were solved, the "Tiffy" became the RAF\'s premier ground-attack aircraft. In the Normandy campaign, Typhoon wings hunted German armour with rockets and cannon to devastating effect.',
    history: [
      'Intended as an interceptor successor to the Hurricane, but its performance above 20,000 ft disappointed. The aircraft found its true role at low level, where its speed and firepower were unmatched.',
      'During the breakout from the Normandy beachhead, Typhoon squadrons under the 2nd Tactical Air Force operated in "cab rank" — circling overhead until called down onto targets by forward air controllers. The Falaise Pocket in August 1944 became a graveyard of German vehicles under their guns.',
      'Its RP-3 60-lb rockets were inaccurate individually but terrifying in salvos. Post-war analysis showed actual tank kills were fewer than claimed — but the psychological effect on German ground troops was immense; surrendering crews often cited "Jabos" as the reason.',
    ],
    notableOperators: ['RAF', '2nd Tactical Air Force'],
    theaters: ['Western Europe'],
    image: wm('Hawker_Typhoon_Mk_IB_MN601_of_No._198_Squadron_RAF.jpg'),
    imageCredit: 'Royal Air Force / IWM — Public Domain',
    wikiSlug: 'Hawker_Typhoon',
    tags: ['Fighter-bomber', 'RAF', 'Ground-attack', 'Rockets'],
  },

  // ──────────────── UNITED STATES ────────────────
  {
    slug: 'p-51-mustang',
    name: 'North American P-51 Mustang',
    designation: 'P-51B / C / D / K',
    nation: 'United States',
    role: 'Long-range escort fighter',
    manufacturer: 'North American Aviation',
    firstFlight: '26 October 1940',
    inService: '1942 – 1984 (various services)',
    produced: '15,586',
    crew: '1',
    engine: 'Packard V-1650 (licence-built Rolls-Royce Merlin 61 series)',
    maxSpeed: '703 km/h',
    ceiling: '12,800 m',
    range: '2,755 km (with drop tanks)',
    armament: '6× .50 cal Browning M2 MGs; 2× 1,000 lb bombs or 10× 5-inch rockets',
    tagline: 'The aircraft that took bomber escort all the way to Berlin.',
    summary:
      'The P-51 began life as a mediocre fighter with an underpowered Allison engine, good only at low altitude. The pairing with the Rolls-Royce Merlin in 1942 transformed it into arguably the finest piston-engine fighter of the war — fast, manoeuvrable, and with a range that changed the shape of the air war over Europe.',
    history: [
      'Originally built to a British specification in just 117 days. Merlin-engined variants entered combat with the USAAF 354th Fighter Group in December 1943 and immediately proved they could escort B-17 and B-24 formations all the way to their targets and back.',
      'The arrival of Mustangs over Berlin in March 1944 broke the back of the Luftwaffe day-fighter force. Aggressive USAAF leadership released escorts to pursue German fighters to their airfields; attrition became one-sided within months.',
      'Aces like George Preddy, Chuck Yeager, and Don Gentile flew Mustangs. In the Pacific, VLR (Very Long Range) Mustangs escorted B-29s from Iwo Jima to the Japanese home islands. The P-51 continued in service into the Korean War and with smaller air forces for decades afterwards.',
    ],
    notableOperators: ['USAAF', 'RAF', 'Royal Australian Air Force', 'Chinese Nationalist Air Force'],
    theaters: ['Western Europe', 'Mediterranean', 'Pacific', 'China-Burma-India'],
    image: wm('North_American_P-51D-5NA_Mustang_-_USAF.jpg'),
    imageCredit: 'USAAF — Public Domain',
    wikiSlug: 'North_American_P-51_Mustang',
    tags: ['Fighter', 'Escort', 'USAAF', 'Long range'],
  },
  {
    slug: 'p-47-thunderbolt',
    name: 'Republic P-47 Thunderbolt',
    designation: 'P-47C / D / M / N',
    nation: 'United States',
    role: 'Fighter / fighter-bomber',
    manufacturer: 'Republic Aviation',
    firstFlight: '6 May 1941',
    inService: '1942 – 1966 (various services)',
    produced: '15,636',
    crew: '1',
    engine: 'Pratt & Whitney R-2800 Double Wasp (2,000–2,800 hp)',
    maxSpeed: '697 km/h',
    ceiling: '13,100 m',
    range: '1,600 km (2,900 km with tanks)',
    armament: '8× .50 cal Browning M2 MGs; up to 1,130 kg bombs and/or 10× 5-inch rockets',
    tagline: 'Seven tons of American industrial muscle with wings.',
    summary:
      'The "Jug" was enormous — the heaviest single-engine fighter to see mass service in WWII. Its P&W R-2800 radial, turbocharger, and eight heavy machine guns made it a powerhouse at altitude and a devastating ground-attack aircraft at low level. Pilots loved its ability to absorb punishment and bring them home.',
    history: [
      'Entered service with the 56th Fighter Group ("Zemke\'s Wolfpack") in Europe in 1943. Though less manoeuvrable than contemporary enemy fighters, its diving speed was unmatched — "dive away" became the universal advice when jumped.',
      'As P-51s took over the escort role in 1944, Thunderbolts turned increasingly to ground attack, blasting locomotives, trains, motor transport, and bridges during the Normandy campaign and beyond. The Ninth Air Force\'s Thunderbolt groups flew thousands of sorties in the ground-attack role.',
      'The long-range P-47N was developed specifically for the Pacific. Built around a wet wing for added fuel capacity, it escorted B-29s on raids against Japan from Ie Shima and Saipan and remained in front-line service until the P-80 jet replaced it.',
    ],
    notableOperators: ['USAAF', 'RAF', 'Free French Air Force', 'Brazilian Air Force'],
    theaters: ['Western Europe', 'Mediterranean', 'Pacific'],
    image: wm('P-47D_23_Zemke.jpg'),
    imageCredit: 'USAAF — Public Domain',
    wikiSlug: 'Republic_P-47_Thunderbolt',
    tags: ['Fighter', 'Ground-attack', 'USAAF', 'Rugged'],
  },
  {
    slug: 'p-38-lightning',
    name: 'Lockheed P-38 Lightning',
    designation: 'P-38F / G / H / J / L',
    nation: 'United States',
    role: 'Twin-engine fighter / long-range escort / photo-reconnaissance',
    manufacturer: 'Lockheed',
    firstFlight: '27 January 1939',
    inService: '1941 – 1965',
    produced: '10,037',
    crew: '1',
    engine: '2× Allison V-1710 V12 (turbocharged)',
    maxSpeed: '667 km/h',
    ceiling: '13,400 m',
    range: '2,100 km (with drop tanks)',
    armament: '1× 20 mm Hispano cannon, 4× .50 cal MGs — all nose-mounted; up to 1,800 kg bombs',
    tagline: 'The forked-tail devil the Germans called "der Gabelschwanz-Teufel."',
    summary:
      'Instantly recognisable with its twin booms and central nacelle, the P-38 was a radical design: twin-engine heavy fighter with turbochargers, tricycle landing gear, and all guns clustered in the nose for concentrated, unconvergent fire. It served in every theatre and in more roles than almost any other American fighter.',
    history: [
      'Early combat in Europe exposed problems with high-altitude engine reliability and compressibility in dives. Later marks (J, L) fixed these issues with dive flaps, improved superchargers, and more powerful engines.',
      'The Lightning was supreme in the Pacific, where long overwater legs and its ability to return home on one engine paid dividends. America\'s two top-scoring aces — Richard Bong (40 kills) and Thomas McGuire (38) — both flew P-38s.',
      'P-38s executed Operation Vengeance on 18 April 1943 — the long-range intercept and shoot-down of Admiral Yamamoto\'s G4M "Betty" transport over Bougainville. Unarmed F-5 photo-reconnaissance variants flew some of the most important strategic intelligence missions of the war.',
    ],
    notableOperators: ['USAAF', 'Free French Air Force'],
    theaters: ['Pacific', 'Mediterranean', 'Western Europe', 'China-Burma-India'],
    image: wm('Lockheed_P-38_Lightning_USAF.JPG'),
    imageCredit: 'USAAF — Public Domain',
    wikiSlug: 'Lockheed_P-38_Lightning',
    tags: ['Fighter', 'Twin-engine', 'USAAF', 'Pacific'],
  },
  {
    slug: 'p-40-warhawk',
    name: 'Curtiss P-40 Warhawk',
    designation: 'P-40B / E / K / N',
    nation: 'United States',
    role: 'Fighter / fighter-bomber',
    manufacturer: 'Curtiss-Wright',
    firstFlight: '14 October 1938',
    inService: '1939 – 1958',
    produced: '13,738',
    crew: '1',
    engine: 'Allison V-1710 V12',
    maxSpeed: '580 km/h',
    ceiling: '8,800 m',
    range: '1,100 km',
    armament: '6× .50 cal MGs; 1× 500 lb bomb',
    tagline: 'Not the best fighter in the war — but a stopgap that held the line everywhere at once.',
    summary:
      'The P-40 lacked the altitude performance of contemporary European fighters, but it was available in huge numbers at a time when the Allies desperately needed any modern fighter at all. From North Africa to China, it fought well enough — and its shark-mouthed nose art made it legendary.',
    history: [
      'Pre-war production priority meant P-40s were present at Pearl Harbor and across the Far East when the war expanded. In the Philippines, Dutch East Indies, and over Darwin, they were outclassed by the A6M Zero but kept fighting.',
      'Became the iconic mount of Claire Chennault\'s American Volunteer Group ("Flying Tigers") in China, whose blue-shark-mouth paint scheme became one of the most famous liveries in aviation history. Tactics of dive-and-zoom, never dogfighting with Zeros, yielded a highly favourable exchange rate.',
      'Served with distinction in North Africa with the RAF and Commonwealth air forces, where its ruggedness and fighter-bomber versatility were valued over outright performance. Remained in production until 1944 despite being obsolete by then.',
    ],
    notableOperators: ['USAAF', 'RAF/Commonwealth', 'Soviet VVS', 'AVG "Flying Tigers"'],
    theaters: ['North Africa', 'Pacific', 'China-Burma-India', 'Eastern Front'],
    image: wm('Curtiss_P-40E_Warhawk_USAF.jpg'),
    imageCredit: 'USAAF — Public Domain',
    wikiSlug: 'Curtiss_P-40_Warhawk',
    tags: ['Fighter', 'USAAF', 'Flying Tigers'],
  },
  {
    slug: 'b-17-flying-fortress',
    name: 'Boeing B-17 Flying Fortress',
    designation: 'B-17E / F / G',
    nation: 'United States',
    role: 'Heavy strategic bomber',
    manufacturer: 'Boeing',
    firstFlight: '28 July 1935',
    inService: '1938 – 1968 (various services)',
    produced: '12,731',
    crew: '10',
    engine: '4× Wright R-1820 Cyclone radial',
    maxSpeed: '462 km/h',
    ceiling: '10,850 m',
    range: '3,220 km with 2,700 kg bomb load',
    armament: '13× .50 cal MGs in turrets and waist positions; up to 3,600 kg bombs internally',
    tagline: 'The bristling, high-altitude icon of daylight strategic bombing.',
    summary:
      'The B-17 embodied the American faith that a heavily-armed, high-flying bomber could fight its way to targets in broad daylight without escort. The theory was tested to destruction over Germany in 1943; the aircraft itself, however, earned undying affection for its ability to limp home with astonishing damage.',
    history: [
      'First combat with the 8th Air Force in August 1942. Early unescorted raids went reasonably well until the Luftwaffe concentrated fighter defence. The missions against Schweinfurt and Regensburg in August and October 1943 cost roughly 60 bombers each — losses that were unsustainable.',
      'The B-17G introduced the chin turret to counter head-on Fw 190 attacks, and improved armour and armament reduced vulnerability. The real solution came with long-range escort — P-51s — from late 1943 onwards, which finally allowed the bomber offensive to grind down German industry.',
      'Famous for bringing crews home against impossible odds: "All Americans" returned to England after losing most of its tail to a collision; "Old 666" fought off twenty Japanese fighters over Bougainville. More than 4,700 B-17s were lost in combat, but the aircraft\'s reputation for survivability was well-earned.',
    ],
    notableOperators: ['USAAF', 'RAF Coastal Command'],
    theaters: ['Western Europe — strategic bombing', 'Pacific (early war)'],
    image: wm('Boeing_B-17E_Flying_Fortress.jpg'),
    imageCredit: 'USAAF — Public Domain',
    wikiSlug: 'Boeing_B-17_Flying_Fortress',
    tags: ['Bomber', 'USAAF', 'Strategic bombing', 'Heavy'],
  },
  {
    slug: 'b-24-liberator',
    name: 'Consolidated B-24 Liberator',
    designation: 'B-24D / H / J / L / M',
    nation: 'United States',
    role: 'Heavy strategic bomber / maritime patrol',
    manufacturer: 'Consolidated Aircraft',
    firstFlight: '29 December 1939',
    inService: '1941 – 1968',
    produced: '18,482 (the most-produced American military aircraft in history)',
    crew: '7 – 11',
    engine: '4× Pratt & Whitney R-1830 Twin Wasp',
    maxSpeed: '488 km/h',
    ceiling: '8,500 m',
    range: '3,400 km with 2,300 kg bombs',
    armament: '10× .50 cal MGs; up to 3,630 kg bombs',
    tagline: 'More bombers built than any other American type of the war.',
    summary:
      'Designed after the B-17 but built in far greater numbers, the B-24 had a longer range, a larger bomb bay, and more fuel — though it was harder to fly and less loved by its crews. It served everywhere: over Germany, over the Atlantic hunting U-boats, and across the vast distances of the Pacific.',
    history: [
      'The high-aspect-ratio Davis wing gave the Liberator range and economy but poor stability at altitude. In the 8th Air Force it flew alongside B-17s; in the 15th Air Force from Italy it was the dominant heavy bomber.',
      'Executed Operation Tidal Wave on 1 August 1943 — the ultra-low-level raid on the Ploești oil refineries in Romania from bases in Libya. Of 177 B-24s launched, 53 were lost; five Medals of Honor were awarded, three of them posthumously.',
      'In its maritime patrol form, the Very Long Range (VLR) Liberator closed the "Mid-Atlantic Gap" — the zone of ocean previously beyond air cover where U-boat wolfpacks had hunted convoys with near-impunity. This contribution to winning the Battle of the Atlantic is often underrated.',
    ],
    notableOperators: ['USAAF', 'RAF Coastal Command', 'Royal Canadian Air Force'],
    theaters: ['Western Europe', 'Mediterranean', 'Pacific', 'Atlantic'],
    image: wm('Consolidated_B-24_Liberator.jpg'),
    imageCredit: 'USAAF — Public Domain',
    wikiSlug: 'Consolidated_B-24_Liberator',
    tags: ['Bomber', 'USAAF', 'Strategic bombing', 'Maritime patrol'],
  },
  {
    slug: 'b-29-superfortress',
    name: 'Boeing B-29 Superfortress',
    designation: 'B-29 / B-29A / B-29B',
    nation: 'United States',
    role: 'Very heavy strategic bomber',
    manufacturer: 'Boeing',
    firstFlight: '21 September 1942',
    inService: '1944 – 1960',
    produced: '3,970',
    crew: '11',
    engine: '4× Wright R-3350 Duplex-Cyclone turbo-supercharged',
    maxSpeed: '574 km/h',
    ceiling: '9,710 m',
    range: '5,600 km with 9,000 kg bombs',
    armament: '10× .50 cal in remote-controlled turrets + 1× 20 mm tail cannon; up to 9,000 kg bombs (20,000 lb)',
    tagline: 'The most expensive weapons programme of WWII — more than the Manhattan Project.',
    summary:
      'The B-29 was a technological quantum leap: pressurised crew compartments, computer-controlled remote gun turrets, and intercontinental range. Its Wright R-3350 engines were so troublesome they killed test pilots; the aircraft was rushed into combat anyway. It ultimately dropped both atomic bombs and firebombed Japan into surrender.',
    history: [
      'Operations began from bases in India and forward fields in China in 1944, striking Japanese targets at extreme range. Results were modest; the bases were logistically untenable.',
      'Redeployed to the Mariana Islands (Saipan, Tinian, Guam) in late 1944. Under General Curtis LeMay, the B-29 force switched from high-altitude precision bombing to devastating low-altitude night incendiary raids. The 9 March 1945 fire raid on Tokyo killed roughly 100,000 civilians in a single night.',
      'On 6 and 9 August 1945 the B-29s "Enola Gay" and "Bockscar" dropped atomic weapons on Hiroshima and Nagasaki. A single B-29, the "Bockscar" crew, ended the war. The aircraft continued to serve through Korea and into the 1950s.',
    ],
    notableOperators: ['USAAF', 'Soviet Air Force (Tu-4 copy)'],
    theaters: ['Pacific — strategic bombing of Japan'],
    image: wm('Boeing_B-29_Superfortress.jpg'),
    imageCredit: 'USAAF — Public Domain',
    wikiSlug: 'Boeing_B-29_Superfortress',
    tags: ['Bomber', 'USAAF', 'Strategic bombing', 'Atomic'],
  },
  {
    slug: 'b-25-mitchell',
    name: 'North American B-25 Mitchell',
    designation: 'B-25B / C / D / G / H / J',
    nation: 'United States',
    role: 'Medium bomber / strafer',
    manufacturer: 'North American Aviation',
    firstFlight: '19 August 1940',
    inService: '1941 – 1979',
    produced: '9,984',
    crew: '5 – 6',
    engine: '2× Wright R-2600 Cyclone',
    maxSpeed: '442 km/h',
    ceiling: '7,600 m',
    range: '2,170 km',
    armament: 'Up to 18× .50 cal MGs (J-model strafer) or 75 mm cannon (G/H); 1,360 kg bombs',
    tagline: 'The aircraft that launched Doolittle\'s raiders off a carrier.',
    summary:
      'The B-25 was a superb medium bomber — rugged, fast for its class, and adaptable. It is best remembered for the Doolittle Raid of April 1942, in which sixteen Mitchells launched from USS Hornet to strike Tokyo, a seemingly impossible operation that gave a wavering America its first morale boost of the war.',
    history: [
      'Following Pearl Harbor, Lt. Col. James Doolittle led sixteen modified B-25Bs off the carrier USS Hornet — a feat never before attempted with medium bombers. They bombed Tokyo and other Japanese cities and then crashed or landed in China. Material damage was light, but the psychological impact on both sides was enormous.',
      'In the South-West Pacific, Maj. Paul "Pappy" Gunn converted B-25s into tree-top strafers with batteries of forward-firing .50 calibre machine guns. These skip-bombed Japanese shipping and shredded airfields from fifty feet.',
      'The B-25H carried an enormous 75 mm cannon in the nose — one of the largest weapons ever mounted in a production aircraft — primarily for anti-shipping work. Mitchells served in every theatre; their name honoured Brig. Gen. Billy Mitchell, the prophet of American airpower.',
    ],
    notableOperators: ['USAAF', 'RAF', 'Soviet VVS', 'Netherlands East Indies', 'Chinese Nationalist AF'],
    theaters: ['Pacific', 'Western Europe', 'Mediterranean', 'China-Burma-India'],
    image: wm('North_American_B-25_Mitchell_USAF.jpg'),
    imageCredit: 'USAAF — Public Domain',
    wikiSlug: 'North_American_B-25_Mitchell',
    tags: ['Bomber', 'USAAF', 'Medium bomber'],
  },
  {
    slug: 'f4u-corsair',
    name: 'Vought F4U Corsair',
    designation: 'F4U-1 / -1A / -1D / F4U-4',
    nation: 'United States',
    role: 'Carrier / land-based fighter / fighter-bomber',
    manufacturer: 'Vought',
    firstFlight: '29 May 1940',
    inService: '1942 – 1965 (various services)',
    produced: '12,571',
    crew: '1',
    engine: 'Pratt & Whitney R-2800 Double Wasp (2,000 hp)',
    maxSpeed: '671 km/h',
    ceiling: '11,200 m',
    range: '1,600 km',
    armament: '6× .50 cal MGs; 2× 1,000 lb bombs or 8× 5-inch rockets',
    tagline: 'The bent-winged bird the Japanese called "Whistling Death."',
    summary:
      'The inverted gull wing — designed to accommodate an outsized propeller without excessively long landing gear — made the Corsair unmistakable. It was the fastest Navy fighter of the war, faster even than many land-based types, and by war\'s end had claimed an 11:1 kill ratio against Japanese aircraft.',
    history: [
      'Initially rejected for carrier service due to poor forward visibility and a bouncy approach; pressed into land-based duty with the Marines on Guadalcanal and through the Solomons from early 1943.',
      'Aces like "Pappy" Boyington of VMF-214 "Black Sheep" flew Corsairs. The Royal Navy in fact qualified the Corsair for carrier operations before the US Navy did, by modifying landing approaches and fitting wing cuffs.',
      'Returned to US carrier service in late 1944 and became a premier fighter-bomber during the Okinawa campaign and strikes against the Japanese home islands. Continued in production into the post-war years and saw extensive service in Korea.',
    ],
    notableOperators: ['US Navy', 'US Marine Corps', 'Royal Navy FAA', 'Royal New Zealand Air Force'],
    theaters: ['Pacific'],
    image: wm('F4U-1A_Corsair_VF-17.jpg'),
    imageCredit: 'US Navy — Public Domain',
    wikiSlug: 'Vought_F4U_Corsair',
    tags: ['Fighter', 'Carrier', 'USN/USMC', 'Pacific'],
  },
  {
    slug: 'f6f-hellcat',
    name: 'Grumman F6F Hellcat',
    designation: 'F6F-3 / -5 / -5N',
    nation: 'United States',
    role: 'Carrier-based fighter',
    manufacturer: 'Grumman',
    firstFlight: '26 June 1942',
    inService: '1943 – 1960',
    produced: '12,275',
    crew: '1',
    engine: 'Pratt & Whitney R-2800 Double Wasp (2,000 hp)',
    maxSpeed: '629 km/h',
    ceiling: '11,400 m',
    range: '1,520 km',
    armament: '6× .50 cal MGs (or 2× 20 mm cannon + 4× .50 cal); 900 kg of bombs or rockets',
    tagline: 'The carrier fighter engineered expressly to kill the Zero — and did.',
    summary:
      'The Hellcat was the workhorse that won the Pacific air war. Designed from hard lessons learned against the Zero, it sacrificed nothing in performance for ruggedness, armour, or firepower. Over the course of the war, Hellcat pilots claimed 5,163 enemy aircraft — over 75% of all US Navy air-to-air victories.',
    history: [
      'Incorporated feedback from an intact A6M2 captured in the Aleutians (the "Akutan Zero"). Designers strengthened the structure, added armour and self-sealing tanks, and mated the airframe to the massive R-2800 radial.',
      'Debuted at Marcus Island in August 1943. During the "Great Marianas Turkey Shoot" in June 1944, Hellcats helped annihilate Japanese carrier air power: roughly 346 Japanese aircraft were shot down for the loss of 30 American.',
      'Produced night-fighter variants with APS-6 radar that hunted Japanese bombers from carrier decks after dark. The kill ratio of 19:1 against all enemy types — 13:1 against the Zero specifically — is one of the most dominant in air combat history.',
    ],
    notableOperators: ['US Navy', 'US Marine Corps', 'Royal Navy FAA'],
    theaters: ['Pacific'],
    image: wm('F6F-3_Hellcat_VF-5_USN.jpg'),
    imageCredit: 'US Navy — Public Domain',
    wikiSlug: 'Grumman_F6F_Hellcat',
    tags: ['Fighter', 'Carrier', 'USN', 'Pacific'],
  },
  {
    slug: 'sbd-dauntless',
    name: 'Douglas SBD Dauntless',
    designation: 'SBD-1 / -3 / -5 / -6',
    nation: 'United States',
    role: 'Carrier-based dive bomber',
    manufacturer: 'Douglas',
    firstFlight: '1 May 1940',
    inService: '1940 – 1959 (various services)',
    produced: '5,936',
    crew: '2',
    engine: 'Wright R-1820 Cyclone',
    maxSpeed: '410 km/h',
    ceiling: '7,800 m',
    range: '1,800 km',
    armament: '2× .50 cal forward + 2× .30 cal rear; 1,020 kg bombs',
    tagline: 'The aircraft that sank Japan\'s carrier fleet in five minutes at Midway.',
    summary:
      'The SBD was obsolete by European standards — slow, fragile, limited in payload — yet it became the most successful naval dive bomber of the war. In the hands of skilled crews using perfected tactics, it delivered blows from which the Imperial Japanese Navy never recovered.',
    history: [
      'At the Battle of Midway on 4 June 1942, SBDs from USS Enterprise and USS Yorktown caught four Japanese fleet carriers — Akagi, Kaga, Sōryū, and Hiryū — with decks full of armed and fuelled aircraft. Within a matter of minutes three were fatally ablaze; the fourth followed later that day.',
      'The Dauntless was exceptionally accurate in the 70-degree dive, aided by the characteristic perforated split dive brakes. It sank more Japanese shipping than any other Allied type during 1942 and served through the Solomons campaign.',
      'Gradually phased out in favour of the more powerful SB2C Helldiver, but many SBD crews preferred the older aircraft for its forgiving handling. The type also served with the US Marines, Free French, and was adopted by the USAAF as the A-24 Banshee.',
    ],
    notableOperators: ['US Navy', 'US Marine Corps', 'USAAF (A-24)', 'Free French'],
    theaters: ['Pacific'],
    image: wm('Douglas_SBD-3_Dauntless.jpg'),
    imageCredit: 'US Navy — Public Domain',
    wikiSlug: 'Douglas_SBD_Dauntless',
    tags: ['Dive bomber', 'Carrier', 'USN', 'Pacific'],
  },
  {
    slug: 'tbf-avenger',
    name: 'Grumman TBF / TBM Avenger',
    designation: 'TBF-1 / TBM-3',
    nation: 'United States',
    role: 'Carrier-based torpedo bomber',
    manufacturer: 'Grumman / General Motors',
    firstFlight: '1 August 1941',
    inService: '1942 – 1960',
    produced: '9,839',
    crew: '3',
    engine: 'Wright R-2600 Cyclone (1,900 hp)',
    maxSpeed: '442 km/h',
    ceiling: '9,200 m',
    range: '1,610 km',
    armament: '2× .50 cal wing MGs, 1× .50 cal turret, 1× .30 cal ventral; 1× 22-inch torpedo or 900 kg bombs',
    tagline: 'The torpedo bomber that replaced a generation of losses at Midway.',
    summary:
      'The Avenger replaced the outclassed TBD Devastator — of which every aircraft in Torpedo Squadron 8 at Midway was shot down. Large, tough, and carrying its torpedo internally in a weapons bay, the TBF became the standard US Navy torpedo bomber and a formidable anti-submarine platform.',
    history: [
      'First combat was disastrous — six Avengers attacked the Japanese carrier fleet at Midway and five were lost — but the aircraft went on to play a central role in sinking the Japanese super-battleships Musashi (October 1944) and Yamato (April 1945), as well as many U-boats in the Atlantic.',
      'A young naval aviator named George H.W. Bush was shot down in a TBM over Chichi Jima in September 1944; he was rescued by a submarine and later became the 41st President of the United States.',
      'Late-war Avengers fitted with search radars operated in "hunter-killer" teams from escort carriers hunting U-boats in the Atlantic. The type continued in carrier service until the 1950s and as a firefighting tanker for decades after that.',
    ],
    notableOperators: ['US Navy', 'US Marine Corps', 'Royal Navy FAA', 'RNZAF'],
    theaters: ['Pacific', 'Atlantic'],
    image: wm('Grumman_TBF-1_Avenger_USN.jpg'),
    imageCredit: 'US Navy — Public Domain',
    wikiSlug: 'Grumman_TBF_Avenger',
    tags: ['Torpedo bomber', 'Carrier', 'USN', 'Pacific'],
  },

  // ──────────────── SOVIET UNION ────────────────
  {
    slug: 'yak-3',
    name: 'Yakovlev Yak-3',
    designation: 'Yak-3',
    nation: 'Soviet Union',
    role: 'Short-range light fighter',
    manufacturer: 'Yakovlev',
    firstFlight: '28 February 1943',
    inService: '1944 – 1952',
    produced: '4,848',
    crew: '1',
    engine: 'Klimov VK-105PF-2 V12',
    maxSpeed: '655 km/h',
    ceiling: '10,700 m',
    range: '650 km',
    armament: '1× 20 mm ShVAK + 2× 12.7 mm UBS (or 1× 20 mm + 2× 12.7 mm)',
    tagline: '"Avoid combat below 5,000 metres with the Yak-3" — Luftwaffe order, 1944.',
    summary:
      'Light, small, and superbly manoeuvrable at low and medium altitudes, the Yak-3 was one of the best dogfighters of the war in its element. It was fast, agile, and designed specifically for the low-altitude air combat that dominated the Eastern Front.',
    history: [
      'A refined development of the Yak-1 line, lighter and structurally cleaner. It first saw combat over Ukraine in the summer of 1944 and quickly established itself as a pilot\'s aircraft at altitudes below 5,000 metres — where most Eastern Front combat took place.',
      'French pilots of the Normandie-Niemen regiment, serving alongside the Soviets, famously chose to keep their Yaks at the end of the war rather than returning home on a Soviet ship — Stalin gave them as a gift; the aircraft flew back to France.',
      'A large proportion of Soviet aces finished the war flying Yaks of various marks. Together with the La-5/-7, the Yak family numerically dominated the Soviet fighter arm in the final years of the war.',
    ],
    notableOperators: ['Soviet VVS', 'Normandie-Niemen (Free French)', 'Polish Air Force'],
    theaters: ['Eastern Front'],
    image: wm('Yakovlev_Yak-3.jpg'),
    imageCredit: 'Wikimedia Commons — CC BY-SA',
    wikiSlug: 'Yakovlev_Yak-3',
    tags: ['Fighter', 'Soviet', 'Eastern Front'],
  },
  {
    slug: 'il-2-sturmovik',
    name: 'Ilyushin Il-2 Sturmovik',
    designation: 'Il-2 / Il-2M / Il-2M3',
    nation: 'Soviet Union',
    role: 'Ground-attack / close air support',
    manufacturer: 'Ilyushin',
    firstFlight: '2 October 1939',
    inService: '1941 – 1954',
    produced: '36,183 (the most-produced military aircraft in history)',
    crew: '1 (later 2)',
    engine: 'Mikulin AM-38F V12',
    maxSpeed: '414 km/h',
    ceiling: '6,000 m',
    range: '720 km',
    armament: '2× 23 mm VYa cannon + 2× 7.62 mm ShKAS; 1× rear 12.7 mm UBT; up to 600 kg bombs or 8× RS-82 rockets',
    tagline: 'Stalin: "The Red Army needs the Il-2 like it needs air and bread."',
    summary:
      'The Il-2 was an armoured flying shell — its pilot, engine, fuel tanks, and radiators were wrapped in an integral steel bathtub of up to 12 mm thickness. Slow and not remotely nimble, it was nevertheless the Red Army\'s indispensable ground-attack weapon, feared by German tank crews as the "Schwarzer Tod" — Black Death.',
    history: [
      'Initial single-seat variants suffered appalling losses to rear-attacking fighters. The addition of a rear gunner from 1942 (Il-2M) improved survival. Stalin famously rebuked the production plant when output lagged, using language that ensured it never lagged again.',
      'Attacked in low-level cannon-and-rocket passes, often in large formations circling their targets in the "Circle of Death." The 37 mm cannon-equipped Il-2M3 variant was designed specifically to kill tanks, and PTAB shaped-charge bomblets devastated German armoured columns at Kursk.',
      'At 36,000+ aircraft, the Il-2 is the most-produced military aircraft ever made. Its successor, the Il-10, continued in service into the 1950s. The type remains a symbol of the Great Patriotic War in Russia today.',
    ],
    notableOperators: ['Soviet VVS', 'Polish Air Force', 'Czechoslovak Air Force'],
    theaters: ['Eastern Front'],
    image: wm('Il-2_Sturmovik.jpg'),
    imageCredit: 'Wikimedia Commons — Public Domain',
    wikiSlug: 'Ilyushin_Il-2',
    tags: ['Ground-attack', 'Soviet', 'Eastern Front', 'Armoured'],
  },
  {
    slug: 'la-5',
    name: 'Lavochkin La-5 / La-7',
    designation: 'La-5 / La-5FN / La-7',
    nation: 'Soviet Union',
    role: 'Fighter',
    manufacturer: 'Lavochkin',
    firstFlight: 'March 1942 (La-5)',
    inService: '1942 – 1954',
    produced: '≈ 15,000 (combined La-5 / La-7)',
    crew: '1',
    engine: 'Shvetsov ASh-82FN radial (1,850 hp)',
    maxSpeed: '648 km/h (La-5FN) — 661 km/h (La-7)',
    ceiling: '10,500 m',
    range: '760 km',
    armament: '2× 20 mm ShVAK (La-5) or 3× 20 mm B-20 (La-7)',
    tagline: 'The radial-engined fighter that clawed back Soviet skies.',
    summary:
      'Developed from the troubled LaGG-3 by replacing its inline engine with a powerful radial, the La-5 and its successor La-7 became the Soviet Union\'s premier low-altitude dogfighters. Rugged, simple, and available in huge numbers, they matched the German Bf 109G and Fw 190 in the environments where most Eastern Front combat occurred.',
    history: [
      'The original LaGG-3 was so unloved that its designation became a bitter joke among pilots ("Varnished Guaranteed Coffin"). The swap to the Shvetsov radial transformed the aircraft\'s performance almost overnight. Debut combat at Stalingrad in late 1942 was a nasty surprise for the Luftwaffe.',
      'Ivan Kozhedub, the highest-scoring Allied ace of the war with 64 victories, flew La-5s and La-7s exclusively. He notably downed a Me 262 with his La-7 in February 1945.',
      'The La-7 was arguably the best Soviet piston fighter of the war — faster than any Luftwaffe fighter below 6,000 m and a match for them above. Its wooden construction kept production costs and strategic-material requirements low, an enormous advantage during wartime.',
    ],
    notableOperators: ['Soviet VVS', 'Czechoslovak Air Force'],
    theaters: ['Eastern Front'],
    image: wm('Lavochkin_La-5.jpg'),
    imageCredit: 'Wikimedia Commons — Public Domain',
    wikiSlug: 'Lavochkin_La-5',
    tags: ['Fighter', 'Soviet', 'Eastern Front'],
  },
  {
    slug: 'pe-2',
    name: 'Petlyakov Pe-2',
    designation: 'Pe-2 / Pe-2FT',
    nation: 'Soviet Union',
    role: 'Fast tactical bomber / dive bomber / recce',
    manufacturer: 'Petlyakov',
    firstFlight: '22 December 1939',
    inService: '1941 – 1954',
    produced: '11,427',
    crew: '3',
    engine: '2× Klimov VK-105PF V12',
    maxSpeed: '580 km/h',
    ceiling: '8,800 m',
    range: '1,160 km',
    armament: '1× 12.7 mm UBS + 3× 7.62 mm ShKAS; up to 1,600 kg bombs',
    tagline: 'The Soviet answer to the Junkers Ju 88 — and every bit as important.',
    summary:
      'The Pe-2 was the most-produced Soviet bomber of the war: fast, sleek, and adaptable as a level bomber, dive bomber, reconnaissance aircraft, and even a heavy fighter. It was known as "Peshka" (the Pawn) and formed the backbone of Soviet tactical bombing from 1941 to the end of the war.',
    history: [
      'Originally designed as a high-altitude heavy fighter before being hastily reworked into a bomber. Its speed was exceptional — it could outrun many contemporary fighters — and its handling rewarded a skilled crew while punishing the careless.',
      'Female pilots of the 125th M.M. Raskova Guards Bomber Aviation Regiment flew Pe-2s into combat throughout the war, distinguishing themselves in the Baltic campaigns and over East Prussia.',
      'Widely used against concentrations of German armour, fortifications, and supply columns. Its successor, the Tu-2, was even more capable but arrived in numbers too late to displace the Pe-2 from the front-line inventory.',
    ],
    notableOperators: ['Soviet VVS'],
    theaters: ['Eastern Front'],
    image: wm('Petlyakov_Pe-2.jpg'),
    imageCredit: 'Wikimedia Commons — Public Domain',
    wikiSlug: 'Petlyakov_Pe-2',
    tags: ['Bomber', 'Soviet', 'Eastern Front', 'Medium bomber'],
  },

  // ──────────────── GERMANY ────────────────
  {
    slug: 'messerschmitt-bf-109',
    name: 'Messerschmitt Bf 109',
    designation: 'Bf 109E / F / G / K',
    nation: 'Germany',
    role: 'Fighter / interceptor / fighter-bomber',
    manufacturer: 'Bayerische Flugzeugwerke / Messerschmitt',
    firstFlight: '28 May 1935',
    inService: '1937 – 1965 (various services)',
    produced: '≈ 33,984',
    crew: '1',
    engine: 'Daimler-Benz DB 601 / 605 inverted V12',
    maxSpeed: '640 km/h (G-6) — 710 km/h (K-4)',
    ceiling: '12,500 m',
    range: '850 km',
    armament: '1× 20/30 mm engine-mounted cannon + 2× 13 mm or 2× 20 mm cowl MGs',
    tagline: 'The hot-rod fighter that fought from the first day to the last.',
    summary:
      'The Bf 109 was a revelation in 1937 and somehow, remarkably, was still in front-line combat in May 1945 — a testament to the strength of its basic design and to the talents of its pilots. More Bf 109s were built than any other fighter ever, and it claimed more air-to-air victories than any other type in history.',
    history: [
      'Gained its reputation in the Spanish Civil War, then dominated early-war skies over Poland, France, and the Low Countries. The Bf 109E ("Emil") met its match in the Spitfire during the Battle of Britain, where its limited range over south-east England proved a critical handicap.',
      'The Bf 109F ("Friedrich") of 1941 was arguably the most elegant of the line; later G-models ("Gustav") sacrificed handling for engine power and heavier armament to counter USAAF heavy bombers. The final K-4 was superb at altitude but flown by pilots with little training.',
      'Erich Hartmann, the highest-scoring fighter pilot in history with 352 victories, flew the Bf 109 exclusively. Post-war, licensed versions continued in Czech, Spanish, and Israeli service into the mid-1960s.',
    ],
    notableOperators: ['Luftwaffe', 'Regia Aeronautica', 'Romanian Air Force', 'Hungarian Air Force', 'Finnish Air Force'],
    theaters: ['Every theatre of the European war'],
    image: wm('Messerschmitt_Bf_109G.jpg'),
    imageCredit: 'Bundesarchiv — CC BY-SA',
    wikiSlug: 'Messerschmitt_Bf_109',
    tags: ['Fighter', 'Luftwaffe', 'Iconic'],
  },
  {
    slug: 'messerschmitt-bf-110',
    name: 'Messerschmitt Bf 110',
    designation: 'Bf 110C / D / F / G',
    nation: 'Germany',
    role: 'Heavy fighter / night fighter / fighter-bomber',
    manufacturer: 'Messerschmitt',
    firstFlight: '12 May 1936',
    inService: '1937 – 1945',
    produced: '6,170',
    crew: '2 – 3',
    engine: '2× Daimler-Benz DB 601 / 605 V12',
    maxSpeed: '595 km/h',
    ceiling: '11,000 m',
    range: '1,500 km',
    armament: '2× 20 mm cannon + 4× 7.92 mm MGs + 1× rear gun; up to 2,000 kg bombs',
    tagline: 'Göring\'s "Zerstörer" — failed by day, feared by night.',
    summary:
      'Conceived as a long-range "destroyer" to escort bombers deep into enemy territory, the Bf 110 was savaged by Hurricanes and Spitfires during the Battle of Britain. It would require an escort itself. Yet as a night-fighter, the Bf 110 was superbly successful, becoming the backbone of the Luftwaffe\'s defensive effort against RAF Bomber Command.',
    history: [
      'Initially successful in Poland and Norway, the Bf 110\'s vulnerability was exposed in 1940. Zerstörergeschwader losses in the Battle of Britain were catastrophic; the type was withdrawn from daylight operations over Britain.',
      'Conversion to the night-fighter role using AI radar sets (Lichtenstein B/C, then SN-2) transformed the aircraft\'s fortunes. Fitted with the lethal "Schräge Musik" upward-firing cannon, Bf 110 night fighters inflicted appalling casualties on RAF heavy bombers.',
      'Major Heinz-Wolfgang Schnaufer, the top-scoring night fighter ace of all time with 121 victories, flew the Bf 110 almost exclusively. Each of his victories likely represented seven Allied airmen dead or captured.',
    ],
    notableOperators: ['Luftwaffe', 'Regia Aeronautica', 'Hungarian Air Force'],
    theaters: ['Western Europe', 'Eastern Front', 'Mediterranean'],
    image: wm('Messerschmitt_Bf_110G-4_night_fighter.jpg'),
    imageCredit: 'Bundesarchiv — CC BY-SA',
    wikiSlug: 'Messerschmitt_Bf_110',
    tags: ['Heavy fighter', 'Night fighter', 'Luftwaffe'],
  },
  {
    slug: 'messerschmitt-me-262',
    name: 'Messerschmitt Me 262 Schwalbe',
    designation: 'Me 262A-1a / A-2a',
    nation: 'Germany',
    role: 'Jet fighter / fighter-bomber / night fighter',
    manufacturer: 'Messerschmitt',
    firstFlight: '18 April 1941 (piston-powered) / 18 July 1942 (jet-powered)',
    inService: '1944 – 1945',
    produced: '1,430',
    crew: '1 (2 in night fighter)',
    engine: '2× Junkers Jumo 004B-1 axial-flow turbojets (900 kgf each)',
    maxSpeed: '870 km/h',
    ceiling: '11,450 m',
    range: '1,050 km',
    armament: '4× 30 mm MK 108 cannon; optional 24× R4M rockets or 2× 500 kg bombs',
    tagline: 'The first operational jet fighter — a century\'s lead compressed into six months.',
    summary:
      'The Me 262 was an aircraft from the future, introduced too late and in too small numbers to alter the course of the war. Its performance advantage over Allied piston fighters was enormous — roughly 190 km/h faster than a P-51 — but its engines were short-lived and Luftwaffe fuel was running out.',
    history: [
      'Development was delayed by engine problems, political interference (Hitler personally demanded the aircraft be reworked as a bomber), and the general collapse of German industry. First combat units formed in July 1944.',
      'Jagdverband 44, led by Adolf Galland, included some of the most experienced Luftwaffe fighter pilots in the war. Using a "boom and zoom" tactic, Me 262s devastated individual bomber formations on several occasions — the R4M rocket especially was a heavy-bomber killer.',
      'Allied response was to ambush Me 262s at their most vulnerable moments — during takeoff and landing — by patrolling airbases. Captured Me 262s after the war contributed directly to the design of early post-war jets in Britain, the United States, and especially the Soviet Union.',
    ],
    notableOperators: ['Luftwaffe', 'Czechoslovak Air Force (Avia S-92 post-war)'],
    theaters: ['Western Europe', 'Defence of the Reich'],
    image: wm('Messerschmitt_Me_262_Schwalbe.jpg'),
    imageCredit: 'US National Archives — Public Domain',
    wikiSlug: 'Messerschmitt_Me_262',
    tags: ['Jet', 'Fighter', 'Luftwaffe', 'Revolutionary'],
  },
  {
    slug: 'focke-wulf-fw-190',
    name: 'Focke-Wulf Fw 190 / Ta 152',
    designation: 'Fw 190A / F / G / D / Ta 152H',
    nation: 'Germany',
    role: 'Fighter / fighter-bomber',
    manufacturer: 'Focke-Wulf',
    firstFlight: '1 June 1939',
    inService: '1941 – 1949',
    produced: '≈ 20,000',
    crew: '1',
    engine: 'BMW 801 radial (A) or Junkers Jumo 213 inline (D)',
    maxSpeed: '656 km/h (A-8) — 750 km/h (Ta 152H)',
    ceiling: '11,400 m (14,800 m Ta 152H)',
    range: '800 km',
    armament: '4× 20 mm MG 151 + 2× 13 mm MG 131; up to 1,000 kg bombs',
    tagline: 'The "Butcher Bird" that gave Spitfire pilots a rude shock in 1941.',
    summary:
      'Kurt Tank\'s radial-engined masterpiece appeared over France in September 1941 and for months outflew the best Spitfire variant the RAF could put up. Sturdy, heavily armed, and beautifully harmonised, the Fw 190 remained competitive to the end of the war and its long-nosed "Dora" and Ta 152 variants were among the finest piston fighters ever flown.',
    history: [
      'Introduced by JG 26 on the Channel coast. Its combination of speed, firepower, and roll rate caught the RAF by surprise — it was the Spitfire Mk.IX that restored parity in mid-1942.',
      'Fw 190s served in every Luftwaffe fighter command, from bomber-destroyer units over the Reich to the ground-attack F/G variants supporting the army. The type was flown by many of Germany\'s top aces and could be configured as an anti-bomber heavyweight with 30 mm cannon and underwing 20 mm gun pods.',
      'The long-nosed Fw 190D-9 "Dora" (with a Junkers Jumo 213 inline engine) and its further-developed cousin the Ta 152H were capable of matching late-war Allied fighters; the Ta 152H held a significant altitude advantage over the P-51. Too few, too late.',
    ],
    notableOperators: ['Luftwaffe', 'Hungarian Air Force', 'Turkish Air Force (post-war)'],
    theaters: ['Every theatre of the European war'],
    image: wm('Focke-Wulf_Fw_190A.jpg'),
    imageCredit: 'Bundesarchiv — CC BY-SA',
    wikiSlug: 'Focke-Wulf_Fw_190',
    tags: ['Fighter', 'Luftwaffe', 'Radial'],
  },
  {
    slug: 'junkers-ju-87-stuka',
    name: 'Junkers Ju 87 Stuka',
    designation: 'Ju 87B / D / G',
    nation: 'Germany',
    role: 'Dive bomber / anti-tank',
    manufacturer: 'Junkers',
    firstFlight: '17 September 1935',
    inService: '1936 – 1945',
    produced: '6,500',
    crew: '2',
    engine: 'Junkers Jumo 211 inline V12',
    maxSpeed: '410 km/h',
    ceiling: '8,200 m',
    range: '1,000 km',
    armament: '2× 7.92 mm wing MGs + twin rear MG; 1,800 kg bombs or 2× 37 mm anti-tank cannon (G-variant)',
    tagline: 'The inverted gull wings and siren howl that announced Blitzkrieg.',
    summary:
      'The Stuka was a dedicated dive bomber whose pinpoint accuracy was the key to the early-war Blitzkrieg. Its Jericho-Trompete sirens, fitted to scream in the dive, were pure psychological warfare. Vulnerable to modern fighters, the type nevertheless remained in production into 1944 because nothing better existed for its job.',
    history: [
      'Catastrophically successful in Poland, France, and the Low Countries, where Allied fighter opposition was overwhelmed. Losses in the Battle of Britain — where the Stuka encountered modern radar-vectored fighters for the first time — forced its withdrawal from western skies.',
      'Flourished again on the Eastern Front, where Soviet fighter opposition was often weak and Stuka formations could hunt Soviet armour with near-impunity. The Ju 87G "Kanonenvogel," carrying two 37 mm cannon, was a dedicated tank-buster.',
      'Hans-Ulrich Rudel, flying Stukas, is credited with destroying an astonishing 519 tanks, a battleship (Marat), and nearly 2,000 other vehicles — one of the most decorated soldiers of the Reich and the only person awarded the Golden Oak Leaves with Swords and Diamonds to the Knight\'s Cross.',
    ],
    notableOperators: ['Luftwaffe', 'Regia Aeronautica', 'Romanian Air Force', 'Hungarian Air Force'],
    theaters: ['Every theatre of the European war'],
    image: wm('Junkers_Ju_87_Stuka.jpg'),
    imageCredit: 'Bundesarchiv — CC BY-SA',
    wikiSlug: 'Junkers_Ju_87',
    tags: ['Dive bomber', 'Luftwaffe', 'Anti-tank'],
  },
  {
    slug: 'heinkel-he-111',
    name: 'Heinkel He 111',
    designation: 'He 111H / P',
    nation: 'Germany',
    role: 'Medium bomber / torpedo bomber / transport',
    manufacturer: 'Heinkel',
    firstFlight: '24 February 1935',
    inService: '1936 – 1958 (various services)',
    produced: '6,508',
    crew: '5',
    engine: '2× Junkers Jumo 211 V12 (H-series)',
    maxSpeed: '440 km/h',
    ceiling: '6,500 m',
    range: '2,300 km (with external fuel)',
    armament: '7× 7.92 mm MGs + 1× 20 mm cannon; up to 2,000 kg bombs',
    tagline: 'The mainstay of the Luftwaffe bomber arm — until there was no bomber arm left.',
    summary:
      'The He 111 defined the Luftwaffe\'s bomber force. Its glazed nose gave it an unmistakable silhouette over London, Rotterdam, Belgrade, and Leningrad. By 1943 it was obsolete, but production continued: there was simply nothing else to take its place, and the Luftwaffe\'s strategic mission was over by then anyway.',
    history: [
      'Developed in the mid-1930s as a "civil airliner" in evasion of Versailles restrictions. Combat-proven in the Spanish Civil War; mainstay of early-war Blitzkrieg campaigns.',
      'Suffered heavily in the Battle of Britain against modern defences. It was never replaced by the planned successor (the disastrous He 177 "Greif" heavy bomber), so the He 111 was pressed into every conceivable role — torpedo bomber in the Arctic, transport at Stalingrad, V-1 launch platform in 1944.',
      'Post-war production continued under licence in Spain as the CASA 2.111, with Rolls-Royce Merlin engines replacing the original Junkers units. Spanish He 111 lookalikes famously stood in for Luftwaffe bombers in the film "Battle of Britain" (1969).',
    ],
    notableOperators: ['Luftwaffe', 'Regia Aeronautica', 'Hungarian Air Force', 'Spanish Air Force'],
    theaters: ['Every theatre of the European war'],
    image: wm('Heinkel_He_111.jpg'),
    imageCredit: 'Bundesarchiv — CC BY-SA',
    wikiSlug: 'Heinkel_He_111',
    tags: ['Bomber', 'Luftwaffe', 'Medium bomber'],
  },

  // ──────────────── JAPAN ────────────────
  {
    slug: 'mitsubishi-a6m-zero',
    name: 'Mitsubishi A6M Zero (Reisen)',
    designation: 'A6M2 / M3 / M5',
    nation: 'Japan',
    role: 'Carrier-based / land-based fighter',
    manufacturer: 'Mitsubishi Heavy Industries',
    firstFlight: '1 April 1939',
    inService: '1940 – 1945',
    produced: '10,939',
    crew: '1',
    engine: 'Nakajima Sakae 12 / 21 radial (940 – 1,130 hp)',
    maxSpeed: '565 km/h',
    ceiling: '10,000 m',
    range: '3,100 km with drop tank',
    armament: '2× 20 mm Type 99 cannon + 2× 7.7 mm MGs; 2× 60 kg bombs',
    tagline: 'The carrier fighter that stunned the Allies in the first year of war.',
    summary:
      'The Zero was a shock to the Allies: a carrier fighter faster, more manoeuvrable, and longer-ranged than anything they possessed. Its secret was extreme weight-saving — no armour, no self-sealing tanks. That compromise made it devastating in the early war and a death trap once Allied fighters learned its vulnerabilities.',
    history: [
      'Covered the attack on Pearl Harbor and swept Allied fighters from the skies of the Philippines, Malaya, and the Dutch East Indies. The Zero\'s range in particular — extraordinary for a fighter of the era — allowed it to appear where it was not expected.',
      'Allied tactics caught up in 1943 and 1944. The "Thach Weave," developed by Lt. Cdr. John Thach of the US Navy, turned the Zero\'s lack of armour into a fatal weakness — any hit from a .50 cal was likely to set it on fire. By 1944, the Zero was increasingly outmatched by the Hellcat, Corsair, and P-38.',
      'Late in the war, Zeros were increasingly used as kamikaze aircraft — the very weight savings that made them so agile made them cheap to expend. The type remained in front-line service to the end, a symbol of Japan\'s fading naval air power.',
    ],
    notableOperators: ['Imperial Japanese Navy Air Service'],
    theaters: ['Pacific', 'China'],
    image: wm('A6M3_Zero_N712Z_1.jpg'),
    imageCredit: 'Wikimedia Commons — CC BY-SA',
    wikiSlug: 'Mitsubishi_A6M_Zero',
    tags: ['Fighter', 'Carrier', 'IJN', 'Pacific', 'Iconic'],
  },
  {
    slug: 'nakajima-ki-43-hayabusa',
    name: 'Nakajima Ki-43 Hayabusa "Oscar"',
    designation: 'Ki-43-I / II / III',
    nation: 'Japan',
    role: 'Army fighter',
    manufacturer: 'Nakajima',
    firstFlight: 'January 1939',
    inService: '1941 – 1945',
    produced: '5,919',
    crew: '1',
    engine: 'Nakajima Ha-25 / Ha-115 radial',
    maxSpeed: '530 km/h',
    ceiling: '11,200 m',
    range: '1,750 km',
    armament: '2× 12.7 mm Ho-103 MGs',
    tagline: 'The Army fighter so agile that Allied pilots mistook it for the Zero.',
    summary:
      'The Ki-43 was the Imperial Japanese Army\'s primary fighter of the war. Lightly built and lightly armed, it excelled at turning combat — arguably more manoeuvrable than even the Zero at low speeds. Like the Zero, it paid the price in lack of protection and firepower once Allied opposition stiffened.',
    history: [
      'Pilots initially disliked the aircraft because it lacked the agility of the biplanes they were used to. The addition of "butterfly" combat flaps transformed its low-speed handling and turned the Ki-43 into a superb dogfighter.',
      'Dominated the opening Japanese Army offensives in Malaya, Burma, and the Philippines. Flying Tiger P-40s and later Commonwealth Hurricanes struggled against the Ki-43 until they learned to avoid turning fights with it.',
      'Manufactured in large numbers and flown to the war\'s end, the Hayabusa never received firepower upgrades comparable to those given to the Zero; it remained under-armed against increasingly well-armoured Allied fighters and bombers.',
    ],
    notableOperators: ['Imperial Japanese Army Air Service', 'Royal Thai Air Force', 'Manchukuo Air Force'],
    theaters: ['Pacific', 'China-Burma-India'],
    image: wm('Nakajima_Ki-43_Hayabusa.jpg'),
    imageCredit: 'Wikimedia Commons — Public Domain',
    wikiSlug: 'Nakajima_Ki-43',
    tags: ['Fighter', 'IJA', 'Pacific'],
  },
  {
    slug: 'aichi-d3a-val',
    name: 'Aichi D3A "Val"',
    designation: 'D3A1 / D3A2',
    nation: 'Japan',
    role: 'Carrier-based dive bomber',
    manufacturer: 'Aichi',
    firstFlight: 'January 1938',
    inService: '1940 – 1945',
    produced: '1,486',
    crew: '2',
    engine: 'Mitsubishi Kinsei radial',
    maxSpeed: '430 km/h',
    ceiling: '10,500 m',
    range: '1,470 km',
    armament: '2× forward 7.7 mm + 1× rear 7.7 mm; 1× 250 kg bomb + 2× 60 kg bombs',
    tagline: 'The dive bomber of Pearl Harbor — and briefly the most effective in the world.',
    summary:
      'The D3A "Val" was the Imperial Japanese Navy\'s primary carrier dive bomber through the first two years of the war. Its elliptical wing and fixed spatted undercarriage gave it a curiously old-fashioned look — but in 1941–1942, in the hands of highly-trained crews, it was devastatingly effective against Allied warships.',
    history: [
      'Participated in the Pearl Harbor attack on 7 December 1941 and in subsequent operations across the Indian Ocean and the Pacific. D3As sank more Allied warships than any other Axis aircraft, including the British heavy cruisers HMS Cornwall and HMS Dorsetshire and the carrier HMS Hermes in April 1942.',
      'The loss of most of Japan\'s experienced naval aviators at Midway and in the Solomons campaign hit the D3A force particularly hard, since accurate dive bombing demanded a great deal of training. By 1943 the aircraft was obsolete.',
      'Late-war D3As were used as land-based bombers and in kamikaze roles. They were succeeded in carrier service by the Yokosuka D4Y Suisei, but the "Val" remained in second-line duty until the end.',
    ],
    notableOperators: ['Imperial Japanese Navy Air Service', 'Royal Thai Air Force'],
    theaters: ['Pacific', 'Indian Ocean'],
    image: wm('Aichi_D3A_Val.jpg'),
    imageCredit: 'US Navy — Public Domain',
    wikiSlug: 'Aichi_D3A',
    tags: ['Dive bomber', 'Carrier', 'IJN', 'Pacific'],
  },
  {
    slug: 'mitsubishi-g4m-betty',
    name: 'Mitsubishi G4M "Betty"',
    designation: 'G4M1 / G4M2',
    nation: 'Japan',
    role: 'Land-based medium bomber / torpedo bomber',
    manufacturer: 'Mitsubishi',
    firstFlight: '23 October 1939',
    inService: '1941 – 1945',
    produced: '2,435',
    crew: '7',
    engine: '2× Mitsubishi Kasei radial',
    maxSpeed: '438 km/h',
    ceiling: '9,200 m',
    range: '6,000 km',
    armament: '4× 7.7 mm MGs + 1× 20 mm tail cannon; 1× torpedo or 1,000 kg of bombs',
    tagline: '"The Flying Lighter" — long range bought with no protection at all.',
    summary:
      'The G4M was designed for the vast distances of the Pacific, and its range was extraordinary. But that range was achieved by packing the wings with unprotected fuel — a single incendiary round would light them up. Its crews called it the "Hamaki" (cigar); Allied pilots called it "the one-shot lighter."',
    history: [
      'Sank the British battleship HMS Prince of Wales and the battlecruiser HMS Repulse off Malaya on 10 December 1941 — the first time capital ships at sea had been sunk purely by aircraft attack. A turning point in naval warfare.',
      'Heavily engaged across the Pacific, especially in the Solomons campaign. On 18 April 1943, a G4M carrying Admiral Isoroku Yamamoto was intercepted and shot down by P-38 Lightnings in Operation Vengeance, a direct result of broken Japanese codes.',
      'Late-war G4M2e variants served as motherships for the desperate Yokosuka MXY-7 Ohka — the rocket-propelled, piloted flying bomb used in kamikaze attacks. The G4M was also the aircraft used to fly Japanese surrender delegations in 1945.',
    ],
    notableOperators: ['Imperial Japanese Navy Air Service'],
    theaters: ['Pacific', 'China'],
    image: wm('Mitsubishi_G4M_Betty.jpg'),
    imageCredit: 'US Navy — Public Domain',
    wikiSlug: 'Mitsubishi_G4M',
    tags: ['Bomber', 'Torpedo bomber', 'IJN', 'Pacific'],
  },

  // ──────────────── ITALY ────────────────
  {
    slug: 'macchi-c202-folgore',
    name: 'Macchi C.202 Folgore',
    designation: 'C.202',
    nation: 'Italy',
    role: 'Fighter',
    manufacturer: 'Aeronautica Macchi',
    firstFlight: '10 August 1940',
    inService: '1941 – 1948',
    produced: '≈ 1,150',
    crew: '1',
    engine: 'Alfa Romeo R.A.1000 R.C.41-I Monsone (licence-built Daimler-Benz DB 601)',
    maxSpeed: '599 km/h',
    ceiling: '11,500 m',
    range: '610 km',
    armament: '2× 12.7 mm Breda-SAFAT MGs (later + 2× 7.7 mm wing MGs)',
    tagline: 'The best Italian fighter of the war — let down by pitiful firepower.',
    summary:
      'The Folgore combined Italian airframe engineering with a German-derived Daimler-Benz engine, and the result was a fighter that could match — and often outfly — the Hurricane and P-40 in North African skies. Its weakness was armament: just two heavy machine guns when Allied fighters mounted eight or more.',
    history: [
      'Entered service with the Regia Aeronautica in North Africa in 1941, where it was immediately superior to its predecessor, the Fiat G.50, and to most of what the RAF then flew in-theatre. Against Spitfire Mk.Vs it was roughly even.',
      'Saw heavy service in North Africa, over Malta, and in the defence of Italy itself. Many of Italy\'s top aces flew the Folgore, including Franco Lucchini and Luigi Gorrini, and some continued to do so in the brief service of the Italian Co-Belligerent Air Force after 1943.',
      'Superseded by the further-developed C.205 Veltro, which mated an even more powerful DB 605 engine and proper cannon armament to the same airframe. The Veltro is arguably the finest Italian fighter of the war, but it was produced in small numbers.',
    ],
    notableOperators: ['Regia Aeronautica', 'Italian Social Republic (ANR)', 'Italian Co-Belligerent Air Force'],
    theaters: ['Mediterranean', 'North Africa'],
    image: wm('Macchi_MC.202_Folgore.jpg'),
    imageCredit: 'Wikimedia Commons — Public Domain',
    wikiSlug: 'Macchi_C.202_Folgore',
    tags: ['Fighter', 'Regia Aeronautica', 'Mediterranean'],
  },
];

export const getAircraftBySlug = (slug: string): Aircraft | undefined =>
  aircraft.find((a) => a.slug === slug);

export const allSlugs = (): string[] => aircraft.map((a) => a.slug);

export const byNation = (nation: Aircraft['nation']): Aircraft[] =>
  aircraft.filter((a) => a.nation === nation);

export const nations: Aircraft['nation'][] = [
  'United Kingdom',
  'United States',
  'Soviet Union',
  'Germany',
  'Japan',
  'Italy',
];

export const alliedNations: Aircraft['nation'][] = [
  'United Kingdom',
  'United States',
  'Soviet Union',
];

export const axisNations: Aircraft['nation'][] = ['Germany', 'Japan', 'Italy'];
